let musicStore = [
    ["gabru gulab warga", "audio/gurnam-songs/Gabru Gulab Warga - Gurnam Bhullar (DJJOhAL.Com).mp3", "images/gurnam-songimages/Gabru Gulab Warga.jpg"],
    ["diamond", "audio/gurnam-songs/Diamond.mp3", "images/gurnam-songimages/diamond.jpg"],
    ["wakh ho jana", "audio/gurnam-songs/Wakh-Ho-Jana(PaglaSongs).mp3", "images/gurnam-songimages/wakh ho jana.jpg"],
    ["beliya", "audio/gurnam-songs/Beliya.mp3", "images/gurnam-songimages/beliya.jpg"],
    ["kabil", "audio/gurnam-songs/Kabil.mp3", "images/gurnam-songimages/kabil.jpg"],
    ["mera yaar", "audio/gurnam-songs/Mera Yaar Lekh.mp3", "images/gurnam-songimages/mera yaar.jpg"],
    ["pagal", "audio/gurnam-songs/Pagal - Gurnam Bhullar.mp3", "images/gurnam-songimages/pagal.jpg"],
    ["pasand bangi", "audio/gurnam-songs/Pasand Bangi.mp3", "images/gurnam-songimages/pasand bangi.jpg"],
    ["soulmate", "audio/arijit-songs/Soulmate Ft Arijit Singh - Badshah (DJJOhAL.Com).mp3", "images/arijit-songimages/soulmate.jpg"],
    ["chaleya", "audio/arijit-songs/Chaleya_64(PagalWorld.com.sb).mp3", "images/arijit-songimages/chaleya.jpg"],
    ["kesariya", "audio/arijit-songs/Kesariya (Brahmastra) - (Raag.Fm).mp3", "images/arijit-songimages/kesariya.jpg"],
    ["phir ur kya chahiye", "audio/arijit-songs/Phir Aur Kya Chahiye (RaagJatt.com).mp3", "images/arijit-songimages/Phir Aur Kya Chahiye.jpg"],
    ["tumhe kitna pyaar karte", "audio/arijit-songs/Tumhe Kitna Pyaar Karte (RaagJatt.com).mp3", "images/arijit-songimages/Tumhe Kitna Pyaar Karte.jpg"],
    ["love ya", "audio/diljit-songs/Love Ya - DjPunjab.Com.Se.mp3", "images/diljit-songimag es/love ya.jpg"],
    ["o sajni re", "audio/arijit-songs/O Sajni Re (RaagJatt.com).mp3", "images/arijit-songimages/O Sajni Re.jpg"],
    ["lutt putt gaya", "audio/arijit-songs/Lutt Putt Gaya (RaagJatt.com).mp3", "images/arijit-songimages/Lutt Putt Gaya.jpg"],
    ["tere pyaar mein", "audio/arijit-songs/Tere Pyaar Mein (RaagJatt.com).mp3", "images/arijit-songimages/Tere Pyaar Mein.jpg"],
    ["goat", "audio/diljit-songs/G O A T.mp3", "images/diljit-songimages/goat.jpg"],
    ["hass hass", "audio/diljit-songs/Hass-Hass-Diljit-Dosanjh-Sia-Greg-Kurstin.mp3", "images/diljit-songimages/hass hass.jpg"],
    ["naina", "audio/trending-songs/_Naina_64(PagalWorld.com.sb).mp3", "images/naina.png"],
    ["jugni", "audio/diljit-songs/Jugni (RaagJatt.com).mp3", "images/diljit-songimages/Jugni.jpg"],
    ["love ya", "audio/diljit-songs/Love Ya - DjPunjab.Com.Se.mp3", "images/diljit-songimages/love ya.jpg"],
    ["magic", "audio/diljit-songs/Magic (RaagJatt.com).mp3", "images/diljit-songimages/Magic.jpg"],
    ["lalkara", "audio/diljit-songs/Lalkara (RaagJatt.com).mp3", "images/diljit-songimages/Lalkara.jpg"],
    ["case", "audio/diljit-songs/Case (RaagJatt.com).mp3", "images/diljit-songimages/Case.jpg"],
    ["ishq tera", "audio/gururandhawa-songs/Ishq-Tera(PaglaSongs).mp3", "images/gururandhawa-songimages/Ishq Tera.jpg"],
    ["raja rani", "audio/gururandhawa-songs/Guru Randhawa - Raja Rani_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Guru Randhawa - Raja Rani.jpg"],
    ["ishare tere", "audio/gururandhawa-songs/Ishare Tere_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Ishare Tere.jpg"],
    ["bottley kholo", "audio/gururandhawa-songs/Bottley Kholo_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Bottley Kholo.jpg"],
    ["pagal", "audio/gururandhawa-songs/_Pagal_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Pagal.jpg"],
    ["punjabiyan di dhee", "audio/gururandhawa-songs/Punjabiyan Di Dhee_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Punjabiyan Di Dhee.jpg"],
    ["doob gaye", "audio/gururandhawa-songs/Doob Gaye_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Doob Gaye.jpg"],
    ["moon rise", "audio/gururandhawa-songs/Moon Rise_64(PagalWorld.com.sb).mp3", "images/gururandhawa-songimages/Moon Rise.jpg"],
    ["Kuch Baatein", "audio/jubin-songs/Kuch Baatein_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Kuch Baatein.jpg"],
    ["Khushi Jab Bhi Teri", "audio/jubin-songs/Khushi Jab Bhi Teri_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Khushi Jab Bhi Teri.jpg"],
    ["Dil Galti Kar Baitha Hai", "audio/jubin-songs/Dil Galti Kar Baitha Hai_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Dil Galti Kar Baitha Hai.jpg"],
    ["Barsaat Ki Dhun", "audio/jubin-songs/Barsaat Ki Dhun_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Barsaat Ki Dhun.jpg"],
    ["O Aasman Wale", "audio/jubin-songs/O Aasman Wale_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/O Aasman Wale.jpg"],
    ["Pehli Baarish Mein", "audio/jubin-songs/_Pehli Baarish Mein_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Pehli Baarish Mein.jpg"],
    ["Tumse Pyaar Karke", "audio/jubin-songs/Tumse Pyaar Karke_64(PagalWorld.com.sb).mp3", "images/jubin-songimages/Tumse Pyaar Karke.jpg"],
    ["Phir Mulaaqat", "audio/jubin-songs/Phir Mulaaqat - WCI (2019).mp3", "images/jubin-songimages/Phir Mulaaqat.jpg"],
    ["laal peeli akhiyaan", "audio/trending-songs/Laal Peeli Akhiyaan_64(PagalWorld.com.sb).mp3", "images/laalpeeliakhiyaan.jpg"],
    ["gulabi sadi", "audio/trending-songs/Gulabi Sadi Ani Lali_64(PagalWorld.com.sb).mp3", "images/gulabisadi.jpg"],
    ["soulmate", "audio/arijit-songs/Soulmate Ft Arijit Singh - Badshah (DJJOhAL.Com).mp3", "images/soulmate.jpg"],
    ["ve haaniyaan", "audio/trending-songs/Ve Haniya_64(PagalWorld.com.sb).mp3", "images/ve_haaniyaan.jpg"],
    ["system pa system", "audio/haryanvi-songs/System-Pa-System(PagalWorld).mp3", "images/cd.jpg"],
    ["dabya ni karde", "audio/haryanvi-songs/Dabya Ni Karde Ndee Kundu 128 Kbps.mp3", "images/cd.jpg"],
    ["2 gulaab", "audio/haryanvi-songs/2 Gulaab_64(PagalWorld.com.sb).mp3", "images/cd.jpg"],
    ["gaadi nuye chalegi", "audio/haryanvi-songs/Gaadi Nuye Chalegi R Maan 128 Kbps.mp3", "images/cd.jpg"],
    ["kale kagaz", "audio/haryanvi-songs/Kale-Kagaz(PagalNew.Com.Se).mp3", "images/cd.jpg"],
    ["gypsy", "audio/haryanvi-songs/Gypsy(PaglaSongs).mp3", "images/cd.jpg"],
    ["been", "audio/haryanvi-songs/Been R Maan 128 Kbps.mp3", "images/cd.jpg"],
    ["aashiq", "audio/haryanvi-songs/_Aashiq_64(PagalWorld.com.sb).mp3", "images/cd.jpg"],
    ["industry baby", "audio/english-songs/INDUSTRY-BABY(PagalNew.Com.Se).mp3", "images/cd.jpg"],
    ["heat waves", "audio/english-songs/Heat-Waves(Pagal-World.Com.In).mp3", "images/cd.jpg"],
    ["i wanna be yours", "audio/english-songs/I-Wanna-Be-Yours(Pagal-World.Com.In).mp3", "images/cd.jpg"],
    ["night changes", "audio/english-songs/Night-Changes-One-Direction(PaglaWorld.com.cm).mp3", "images/cd.jpg"],
    ["stay", "audio/english-songs/Stay(PagalWorld).mp3", "images/cd.jpg"],
    ["dandelions", "audio/english-songs/Dandelions_64(PagalWorld).mp3", "images/cd.jpg"],
    ["spectre", "audio/english-songs/[drczic]_alan walker_spectre_audio.mp3", "images/cd.jpg"],
    ["faded", "audio/english-songs/Faded(PaglaSongs).mp3", "images/cd.jpg"],
    ["milne hai mujhse aayi", "audio/albums/aashiqui 2/Milne Hai Mujhse Aayi - PagalSongs.com.mp3", "images/cd.jpg"],
    ["aasan nahin yahan", "audio/albums/aashiqui 2/Aasan Nahin Yahan - PagalSongs.com.mp3", "images/cd.jpg"],
    ["bhula dena", "audio/albums/aashiqui 2/Bhula Dena - PagalSongs.com.mp3", "images/cd.jpg"],
    ["chahun main ya naa", "audio/albums/aashiqui 2/Chahun Main Ya Naa - PagalSongs.com.mp3", "images/cd.jpg"],
    [",eri aashiqui", "audio/albums/aashiqui 2/Meri Aashiqui - PagalSongs.com.mp3", "images/cd.jpg"],
    ["piya aaye na", "audio/albums/aashiqui 2/Piya Aaye Na - PagalSongs.com.mp3", "images/cd.jpg"],
    ["sunn raha hai", "audio/albums/aashiqui 2/Sunn Raha Hai - PagalSongs.com.mp3", "images/cd.jpg"],
    ["tum hi ho", "audio/albums/aashiqui 2/Tum Hi Ho - PagalSongs.com.mp3", "images/cd.jpg"],
    ["arjan vailly", "audio/albums/animal/Arjan-Vailly(PaglaSongs).mp3", "images/cd.jpg"],
    ["satranga", "audio/albums/animal/Satranga_64(PagalWorld.com.sb).mp3", "images/cd.jpg"],
    ["pehle bhi main", "audio/albums/animal/Marham-(Pehle-Bhi-Main)(PaglaSongs).mp3", "images/cd.jpg"],
    ["abrar's entry jamal kudu", "audio/albums/animal/Abrar'S-Entry-Jamal-Kudu(PaglaSongs).mp3", "images/cd.jpg"],
    ["haiwaan", "audio/albums/animal/Haiwaan(PaglaSongs).mp3", "images/cd.jpg"],
    ["kashmir", "audio/albums/animal/Kashmir(PaglaSongs).mp3", "images/cd.jpg"],
    ["saari duniya jalaa denge", "audio/albums/animal/Saari-Duniya-Jalaa-Denge(PaglaSongs).mp3", "images/cd.jpg"],
    ["papa meri jaan", "audio/albums/animal/Papa-Meri-Jaan(PaglaSongs).mp3", "images/d.jpg"],
    ["admirin you", "audio/albums/making memories/Admirin You (feat. Preston Pablo) - Karan Aujla.mp3", "images/d.jpg"],
    ["bachke bachke", "audio/albums/making memories/Bachke Bachke (feat. Yarah) - Karan Aujla.mp3", "images/d.jpg"],
    ["champions anthem", "audio/albums/making memories/Champions Anthem - Karan Aujla.mp3", "images/d.jpg"],
    ["girl, i love you", "audio/albums/making memories/Girl, I Love You (Euro S Intro) - Karan Aujla.mp3", "images/d.jpg"],
    ["jee ni lagda", "audio/albums/making memories/Jee Ni Lagda - Karan Aujla.mp3", "images/d.jpg"],
    ["softly", "audio/albums/making memories/Softly - Karan Aujla.mp3", "images/d.jpg"],
    ["try me", "audio/albums/making memories/Try Me - Karan Aujla.mp3", "images/d.jpg"],
    ["tum hi aana", "audio/albums/marjaavan/Tum Hi Aana - Marjaavaan (2019).mp3", "images/d.jpg"],
    ["thodi jagah", "audio/albums/marjaavan/Thodi Jagah - Marjaavaan (2019).mp3", "images/d.jpg"],
    ["kinna sona", "audio/albums/marjaavan/Kinna Sona - Marjaavaan (2019).mp3", "images/d.jpg"],
    ["ek toh kum zindagani", "audio/albums/marjaavan/Ek Toh Kum Zindagani - Marjaavaan (2019).mp3", "images/d.jpg"],
    ["cheques", "audio/albums/still rollin/Cheques_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
    ["og", "audio/albums/still rollin/_OG_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
    ["still rollin", "audio/albums/still rollin/Still Rollin_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
    ["ice", "audio/albums/still rollin/_Ice_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
    ["ruthless", "audio/albums/still rollin/_Ruthless_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
    ["the flow", "audio/albums/still rollin/The Flow_64(PagalWorld.com.sb).mp3", "images/d.jpg"],
]
let url = new URL(window.location.href)
let urlParam = new URLSearchParams(url.search)
let search = urlParam.get("search")
let container = document.querySelector(".container")
musicStore.forEach( song => {
    if (search.toLowerCase() == song[0]){
        container.innerHTML = `<div class="item">
            <img src="${song[2]}">
            <h2>${song[0]}</h2>
            <audio controls="">
                <source src="${song[1]}" type="audio/mpeg">
            </audio>
        </div>`
    }
})